import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { redirect } from "next/navigation";
import { headers } from "next/headers";
import { getCurrentSession } from "@/app/auth/session";
import LougoutButton from "@/app/auth/logoutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AUTH_ROUTES = ["/auth/login", "/auth/register"];

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const path = (await headers()).get("next-url") || "";
  console.log("path", path);
  const { session, user } = await getCurrentSession();

  const onAuthPage = AUTH_ROUTES.some((p) => path.indexOf(p) !== -1);

  if (!onAuthPage && (!session || !user)) {
    redirect("/auth/login");
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {!onAuthPage && (
          <div className="bg-gray-100 text-end">
            <div className="flex flex-row-reverse align-center bg-white shadow-md p-4 gap-4">
              <LougoutButton />
              <p className="text-xl text-gray-700 py-2">
                Hello {user?.username}
              </p>
            </div>
          </div>
        )}
        {children}
      </body>
    </html>
  );
}
